### PR TITLE
Update dependencies versions

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Update version of various dependencies:

- [x] GitHub API - org.kohsuke github Version:1.90 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14958
- [x] jjwt Version 0.9.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14959
- [x] google-api-client Version 1.23.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14960
- [x] Google Guava 23.4-jre https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14961
- [x] google-http-client Version 1.23.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14962
- [x] google-http-client-jackson2 v1.23.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14963
- [x] google-oauth-client v1.23.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14964
- [x] gson 2.8.2 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14965
- [x] h2 database Version: 1.4.196 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14966
- [x] flyway-core 4.2.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14689

### CODE REVIEW

**Comment by benoitf** [comment]
FYI Guava 23.5 is out

**Comment by mkuznyetsov** [comment]
Added new version of Flyway core - 4.2.0

**Review by skabashnyuk — APPROVED** [review]
Go if CI test is ok

**Comment by mkuznyetsov** [comment]
CI tests attached in related Che PR https://github.com/eclipse/che/pull/7711

**Review by riuvshin — APPROVED** [review]

**Pull request merged**
