### PR TITLE
Adding logstash-logback-encoder 4.11 (che#6537)

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
Adding logstash-logback-encoder dependency (#6537)

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/6537

This PR is needed for 
  
  - https://github.com/eclipse/che-lib/pull/42
  - https://github.com/eclipse/che/pull/6539

CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14394

### CODE REVIEW

**Review by riuvshin — APPROVED** [review]
LGTM if this does not require CQ

**Comment by sunix** [comment]
CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14394

**Review by skabashnyuk — APPROVED** [review]
@sunix  can you make sure that logstash-logback-encoder doesn't provide additional transitive dependencies.

**Comment by sunix** [comment]
CQ approved, merging

**Comment by sunix** [comment]
@skabashnyuk 
looks fine (just added the library as a dependency for testing mvn dependency:tree):
```
[INFO] --- maven-dependency-plugin:3.0.1:tree (default-cli) @ maven-depmgt-pom ---                                                            
[INFO] org.eclipse.che.depmgt:maven-depmgt-pom:pom:5.21.0-SNAPSHOT                                                                            
[INFO] \- net.logstash.logback:logstash-logback-encoder:jar:4.11:compile                                                                      
[INFO]    +- ch.qos.logback:logback-core:jar:1.2.1:compile                                                                                    
[INFO]    \- com.fasterxml.jackson.core:jackson-databind:jar:2.7.7:compile                                                                    
[INFO]       +- com.fasterxml.jackson.core:jackson-annotations:jar:2.7.7:compile                                                              
[INFO]       \- com.fasterxml.jackson.core:jackson-core:jar:2.7.7:compile
```

**Pull request merged**
