### PR TITLE
Update kubernetes-client to 2.1.1 (CQ 12789)

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?

Update fabric8io kubernetes-client and openshift-client for some bugfixes.

### Changelog
Updated kubernetes-client and openshift-client from 1.4.31 to 2.1.1 

CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12789

### CODE REVIEW

**Comment by skabashnyuk** [comment]
@amisevsk can you confirm that transitive dependencies remain the same? I mean  ```mvn dependency:tree``` has no changes at all?

**Comment by skabashnyuk** [comment]
```
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
-    <mockwebserver.version>0.0.4</mockwebserver.version>
-    <okhttp.version>3.4.1</okhttp.version>
-    <okhttp.bundle.version>3.4.1_1</okhttp.bundle.version>
-    <okio.version>1.9.0</okio.version>
-    <okio.bundle.version>1.9.0_1</okio.bundle.version>
+    <mockwebserver.version>0.0.12</mockwebserver.version>
+    <okhttp.version>3.6.0</okhttp.version>
+    <okhttp.bundle.version>3.6.0_1</okhttp.bundle.version>
+    <okio.version>1.11.0</okio.version>
+    <okio.bundle.version>1.11.0_1</okio.bundle.version>
     <generex.version>1.0.1</generex.version>
     <generex.bundle.version>1.0.1_1</generex.bundle.version>
     <automaton.version>1.11-8</automaton.version>
     <automaton.bundle.version>1.11-8_1</automaton.bundle.version>
-    <jackson.version>2.7.5</jackson.version>
+    <jackson.version>2.7.7</jackson.version>
     <junit.version>4.12</junit.version>
-    <kubernetes.model.version>1.0.65</kubernetes.model.version>
+    <kubernetes.model.version>1.0.67</kubernetes.model.version>
     <log4j.version>2.5</log4j.version>
     <zjsonpatch.version>0.3.0</zjsonpatch.version>
```
looks like some transitive dependencies has changed. Can you review them and align them with che?

**Comment by amisevsk** [comment]
@skabashnyuk You're right, this is a mistake on my part. I'll look into it.

**Review by bmicklea — APPROVED** [review]

**Comment by amisevsk** [comment]
@skabashnyuk It's looking like we'll need to update the kubernetes-client dependency again before the openshift-connector branch is merged into master, so to simplify things I've moved to merge these changes into a new branch, `openshift-connector`. Having this branch would allow us to continue to work on OpenShift integration without interfering with main Che development, and allow us to round up all the dependency changes (and associated CQs) at once. 

WDYT?

**Comment by skabashnyuk** [comment]
ok. if it's not in master

**Review by l0rd — APPROVED** [review]

**Pull request merged**
