### PR TITLE
Add jsinterop-annotations dependency

### PR DESCRIPTION
**Pull request by azatsarynnyy**
### What does this PR do?
Adds `jsinterop-annotations` dependency.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7352

CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=15002

`jsinterop-annotations` is needed for https://github.com/eclipse/che/pull/7515

### CODE REVIEW

**Comment by skabashnyuk** [comment]
maven dependency tree please

**Review by vparfonov — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
We should add jsinterop base artifact as well
(Or I will provide a separate Pull request)

**Comment by azatsarynnyy** [comment]
@benoitf provide a separate PR, please.

**Comment by azatsarynnyy** [comment]
@skabashnyuk 
```
[INFO] +- com.google.jsinterop:jsinterop-annotations:jar:1.0.2:compile
[INFO] +- org.vectomatic:lib-gwt-svg:jar:0.5.12:provided
[INFO] +- com.google.gwt.gwtmockito:gwtmockito:jar:1.1.8:test
[INFO] +- javax.ws.rs:javax.ws.rs-api:jar:2.0:test
[INFO] +- junit:junit:jar:4.11:test
```

**Comment by benoitf** [comment]
OK Artem. I asked Sharon to validate the two CQs so I wanted to do only one PR but I'm fine with another PR

**Pull request merged**
