### PR TITLE
Upgrade tomcat to 8.0.32 version

### PR DESCRIPTION
**Pull request by mkuznyetsov**
This will fix swagger not working without trailing slash

### CODE REVIEW

**Comment by mkuznyetsov** [comment]
[Eclipse CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11107) has been approved

**Comment by skabashnyuk** [comment]
ok

**Comment by akorneta** [comment]
ok

**Comment by mshaposhnik** [comment]
fine

**Pull request merged**
