### PR TITLE
Add Keycloak dependencies

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Add Keycloak related dependencies

List of related CQs:
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13864 Keycloak Servlet Filter Adapter 3.1.0.Final
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13869 Keycloak Core 3.1.0.Final
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13878 Keycloak Common 3.1.0.Final
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13879 Keycloak Adapter SPI 3.1.0.Final
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13880 Keycloak Servlet Integration 3.1.0.Final
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13881 Keycloak Adapter Core 3.1.0.Final
- [ ] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13882 Keycloak Client Registration API 3.1.0.Final
- [x] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13885 commons-logging 1.2
- [x] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13886 jboss-logging 3.3.0.Final
- [x] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13887 Apache HttpComponets HttpClient 4.5

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5437

### CODE REVIEW

**Comment by riuvshin** [comment]
@mkuznyetsov are you sure that this PR should be merged to master?

**Comment by skabashnyuk** [comment]
@mkuznyetsov  can you show me dependency tree.
@riuvshin no we don't. We will now what closer to finish of feature implementation.

**Comment by riuvshin** [comment]
@skabashnyuk got it, thanks

**Comment by mkuznyetsov** [comment]
@skabashnyuk trees for dependencies
```
+- org.keycloak:keycloak-servlet-filter-adapter:jar:3.1.0.Final:compile
|  +- org.keycloak:keycloak-core:jar:3.1.0.Final:compile
|  |  +- org.keycloak:keycloak-common:jar:3.1.0.Final:compile
|  |  \- org.bouncycastle:bcpkix-jdk15on:jar:1.51:compile
|  +- org.keycloak:keycloak-adapter-spi:jar:3.1.0.Final:compile
|  +- org.keycloak:keycloak-servlet-adapter-spi:jar:3.1.0.Final:compile
|  |  \- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
|  +- org.keycloak:keycloak-adapter-core:jar:3.1.0.Final:compile
|  +- org.apache.httpcomponents:httpclient:jar:4.5:compile
|  |  +- org.apache.httpcomponents:httpcore:jar:4.4.1:compile
|  |  +- commons-logging:commons-logging:jar:1.2:compile
|  |  \- commons-codec:commons-codec:jar:1.10:compile
|  +- org.bouncycastle:bcprov-jdk15on:jar:1.51:compile
|  +- com.fasterxml.jackson.core:jackson-core:jar:2.7.7:compile
|  +- com.fasterxml.jackson.core:jackson-databind:jar:2.7.7:compile
|  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.7.7:compile
+- org.keycloak:keycloak-client-registration-api:jar:3.1.0.Final:compile
|  +- org.keycloak:keycloak-core:jar:3.1.0.Final:compile
|  +- org.apache.httpcomponents:httpclient:jar:4.5:compile
|  |  +- org.apache.httpcomponents:httpcore:jar:4.4.1:compile
|  |  +- commons-logging:commons-logging:jar:1.2:compile
```

**Comment by skabashnyuk** [comment]
I've created a new pr https://github.com/eclipse/che-dependencies/pull/57

**Pull request closed without merging**
