### PR TITLE
added lombok dependancy

### PR DESCRIPTION
**Pull request by KakashiMamun**
Added dependancy for plugin-lombok. 

https://github.com/eclipse/che/pull/3288

### CODE REVIEW

**Comment by benoitf** [comment]
adding dependency on an eclipse project need to first be accepted with IpZilla
https://dev.eclipse.org/ipzilla/

it seems version 1.14.8 was approved for some other projects
https://dev.eclipse.org/ipzilla/buglist.cgi?query_format=advanced&short_desc_type=allwordssubstr&short_desc=lombok&long_desc_type=substring&long_desc=&bug_file_loc_type=allwordssubstr&bug_file_loc=&keywords_type=allwords&keywords=&emailassigned_to1=1&emailtype1=substring&email1=&emailassigned_to2=1&emailreporter2=1&emailcc2=1&emailtype2=substring&email2=&bugidtype=include&bug_id=&chfieldfrom=&chfieldto=Now&chfieldvalue=&cmdtype=doit&order=Reuse+same+sort+as+last+time&field0-0-0=noop&type0-0-0=noop&value0-0-0=

**Comment by KakashiMamun** [comment]
I cant login to ipZilla. so you want me to change it to 1.14.8 ?

**Comment by skabashnyuk** [comment]
You have to create CQ in any case. Even for already approved for other projects (it's not approved for che now) please read https://wiki.eclipse.org/Development_Resources/Contribution_Questionnaire

BTW how are you going to exclude PrettyCommentsPrinter class from Che packaging?

**Comment by KakashiMamun** [comment]
I am new in Contributing to Open source projects. So can you tell me PrettyCommentsPrinter class should be excluded ? I can exclude the class while creating my plugin.

**Comment by skabashnyuk** [comment]
this CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9166 approves without PrettyCommentsPrinter class. It mean that jar that lombok dependency should not contains this class. Can you confirm that?

**Comment by KakashiMamun** [comment]
@skabashnyuk , I dont know how to remove a class from jar. as i commented in another thread that I am repacking lombok and excluding the org.lombok from project dependancy, is it okay if i exclude PrettyCommentsPrinter  class when I repack the lombok files ? can you kindly suggest me better solution ?

**Comment by skabashnyuk** [comment]
Since https://github.com/eclipse/che/pull/3288 already closed

**Pull request closed without merging**
