### PR TITLE
INFRA-54: Add language server version properties

### PR DESCRIPTION
**Pull request by tolusha**
### Reference issue
https://github.com/codenvy/infrastructure/issues/54

### CODE REVIEW

**Comment by benoitf** [comment]
Where are the sources for org.eclipse.che.ls binaries ?

**Comment by riuvshin** [comment]
@benoitf we hosted them on our nexus, afaik we don;t have sources for them just binaries

**Review by riuvshin — APPROVED** [review]

**Comment by benoitf** [comment]
it's still compliant with EPL ?

**Comment by riuvshin** [comment]
@benoitf good catch... seems we are not able to do this.

**Pull request closed without merging**
