### PR TITLE
Add flyway & postgres dependencies

### PR DESCRIPTION
**Pull request by voievodin**
Those dependencies needed by [THIS](https://github.com/eclipse/che/pull/3063) pull request.
Requires [flyway](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12208) cq.

@skabashnyuk please review

### CODE REVIEW

**Comment by benoitf** [comment]
what is cq for postgresql ?

**Comment by voievodin** [comment]
going to make PB for it, thx

**Comment by voievodin** [comment]
[Postgres](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12291) was approved, waiting for Flyway approval.

**Review by skabashnyuk — APPROVED** [review]
@evoevodin you can proceed with checkin.

**Pull request merged**
