### PR TITLE
CHE-614 used latest everrest version

### PR DESCRIPTION
**Pull request by skabashnyuk**

### CODE REVIEW

**Comment by benoitf** [comment]
I'm not sure we can use external snapshot dependencies without previously approved CQ

**Comment by vparfonov** [comment]
+1

**Comment by skabashnyuk** [comment]
I'm working on that

**Comment by garagatyi** [comment]
I don't think we should use external snapshot dependency at all

**Comment by skabashnyuk** [comment]
Tag set. Working on CQ

**Comment by skabashnyuk** [comment]
CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11018

**Pull request merged**
