### PR TITLE
Add selenium property

### PR DESCRIPTION
**Pull request by tolusha**
Adds dependencies for selenium tests for Eclipse Che project (an issue codenvy/qa#978).

### CODE REVIEW

**Comment by skabashnyuk** [comment]
how it used?

**Comment by riuvshin** [comment]
do we have CQ for selenium and it's dependencies?

**Comment by tolusha** [comment]
@skabashnyuk 
It will be used in the selenium module of the che project.

@riuvshin 
I think it is a question for @vkuznyetsov 
I've created PR in the fork, it doesn't break anything for now

**Comment by skabashnyuk** [comment]
It will be used in the selenium module of the che project. - how?

**Comment by skabashnyuk** [comment]
If it used for dependencies declaration when they have to be declared here in one place.

**Comment by tolusha** [comment]
@skabashnyuk 
ah) I've just forgotten to commit the rest of the changes. thx

**Comment by skabashnyuk** [comment]
is this test only dependency?

**Comment by tolusha** [comment]
Yes, build & test dependency

**Comment by tolusha** [comment]
Related PRs
https://github.com/eclipse/che/pull/5759
https://github.com/codenvy/codenvy/pull/2336/files
https://github.com/codenvy/saas/pull/240/files

CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13952
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13914

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
