### PR TITLE
CHE-2506: Add io.typfox.lsapi dependency

### PR DESCRIPTION
**Pull request by tolusha**

### CODE REVIEW

**Comment by skabashnyuk** [comment]
is this an Eclipse project?

**Comment by tolusha** [comment]
yes
https://projects.eclipse.org/proposals/lsp4j

**Review by benoitf — CHANGES_REQUESTED** [review]
I'm not sure a proposal can be considered as Eclipse Project
It needs to be incubated and get packages org.eclipse, etc
So I think it requires a CQ on ipzilla

**Comment by tolusha** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12000

**Review by benoitf — APPROVED** [review]
CQ validated as parallel ip

**Pull request merged**
