### PR TITLE
Add string template version

### PR DESCRIPTION
**Pull request by benoitf**
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11985

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Does this dependency has transitive dependencies.
Are they are all aligned with our existed dependencies?

**Comment by benoitf** [comment]
you may check transitive dependencies on https://github.com/antlr/stringtemplate4/blob/master/pom.xml

AFAIK it seems ok with our existing dependencies

**Comment by benoitf** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11985 has been approved

@riuvshin @skabashnyuk

**Review by skabashnyuk — APPROVED** [review]

**Comment by riuvshin** [comment]
+1

**Pull request merged**
